### ISSUE TITLE
Xquartz download link is not working

### ISSUE THREAD

**Issue by pongstr** [boxen/puppet-xquartz#13]
- Current Link:   http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg
- Updated Link: http://xquartz-dl.macosforge.org/SL/XQuartz-2.7.7.dmg

please see PR #12

**Comment by jonstorer** [comment]
:+1:

**Comment by pongstr** [comment]
PR was 2yrs old. Thanks for updating though.
